blank_issues_enabled: false
contact_links:
  - name: Question?
    url: https://github.com/EddieHubCommunity/CreatorsRegistry/discussions
    about: If your question is not covered by the FAQs, please ask your question in our GitHub Discussions.
